name: tourbillon_clock
description: Flutter Clock Challenge

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

  flare_flutter: ^1.8.3
  google_fonts: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - animations/
  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: third_party/LibreBaskerville-Bold.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: third_party/PlayfairDisplay-Bold.ttf